name: weather
description: Beautiful Weather App with support for dark mode. Created by Daniel Girotto.



publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: '>=2.12.1 <3.0.0'



dependencies:
  cool_alert: ^2.0.1
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.2
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.7.0
  geocoding: ^3.0.0
  geolocator: ^11.0.0
  google_fonts: ^6.2.1
  status_alert: ^1.0.1





dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true



  fonts:
    - family: WeatherIcons
      fonts:
        - asset: fonts/weathericons-regular.ttf

